language: erlang
matrix:
  include:
    - os: linux
      otp_release: 17.5
    - os: linux
      otp_release: 18.3
    - os: linux
      otp_release: 19.3
    - os: linux
      otp_release: 20.0
    - os: linux
      otp_release: 21.0
    - os: osx
      language: generic
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  ## should eventually use a tap that has previous erlang versions here
  ## as this only uses the latest erlang available via brew
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install erlang; fi
before_script: "./bootstrap"
script: ""
branches:
  only:
  - master
  - hex_core
  - feature/private_canary_build
cache:
  directories:
  - "$HOME/.cache/rebar3/hex/default"
deploy:
  - provider: releases
    api_key:
      secure: MjloYuaQF3cd3Oab57zqwPDLPqt5MDgBIrRLpXOQwNovr2tnkKd4aJK3QJ3pTxvZievjgl+qIYI1IZyjuRV37nkjAfMw14iig959wi0k8XTJoMdylVxE5X7hk4SiWhX/ycnJx3C28PPw1OitGTF76HAJDMgEelNdoNt+hvjvDEo=
    file: rebar3
    on:
      repo: erlang/rebar3
      tags: true
  - provider: s3
    access_key_id: AKIAJAPYAQEFYCYSNL7Q
    secret_access_key:
      secure: "BUv2KQABv0Q4e8DAVNBRTc/lXHWt27yCN46Fdgo1IrcSSIiP+hq2yXzQcXLbPwkEu6pxUZQtL3mvKbt6l7uw3wFrcRfFAi1PGTITAW8MTmxtwcZIBcHSk3XOzDbkK+fYYcaddszmt7hDzzEFPtmYXiNgnaMIVeynhQLgcCcIRRQ="
    skip_cleanup: true
    local-dir: _build/prod/bin
    bucket: "rebar3-nightly"
    acl: public_read
    on:
      repo: erlang/rebar3
      branch: master
      condition: $TRAVIS_OTP_RELEASE = "17.5"

  - provider: s3
    region: us-west-2
    access_key_id: AKIAJURSJQAHFRCRGOQQ
    secret_access_key:
      secure: "eBw+mSUEQXRt0mNRMbo3qQ8zQBKKack66lI99WM+ZeT98cHMj/noUk8/6DCBP1580oaBCYlcIPhyOAt3sheqa33iX32JOh4jZh5vagp6MK8wKyMOeUpZ8PMmrNZa+L94C0N3GTRQ+VloNEOegneoT8hPuN2hdyyGp8Ed7OivDlfqVQfdA+GiUYz9ZisEM9xSsj+bayZM1DfExOwO7/B1+Q8Ta9OAxUTdPVRpap4FdCDrJDqpcLvAJgNffKbApsAZDLOJHT/U3/llE33kpjvZd7I9ORV//PscUPXjJRE+N65PMlXsB/Ujwi+BSAxnIoOpAvvt5yxPoB0Man7nR9cjQ+yxvitGgixIlHdUoTrFwVaV8IGkEVEHezNlTP2SykeeGGItqFZplqMturEIRaZ8xPCBQANUW5iZcg5DNcgFWd87t7I4PjTLIEhd3JRtNzhx1M+IRR1p33TivQPlylGFWVySdLQdyMVDaaQbSI0IdtU8sVdWFrErQx51R2JHOf70VMXlsII+HmRmTpR56ZwShZqT92hnkN9ghbcIWb53xhQnm4Bleq+8iPkS+tEvx65OBoaFA/eDPJnszdP76wf52Aw8AujFmIMAwhOyAFI4i1tFOkPhi/7/9CEN2ldHiSayFvaQ+Ddbgcgs8Bltw1f30UKnX6AbVBc4Ml92EzuPjNI="
    skip_cleanup: true
    local-dir: _build/canary/bin
    bucket: "rebar3-canary"
    region: "us-west-2"
    upload-dir: "canary"
    acl: public_read
    on:
      repo: lrascao/rebar3
      branch: feature/private_canary_build
      condition: $TRAVIS_OTP_RELEASE = "17.5" && $TRAVIS_EVENT_TYPE = cron && $TRAVIS_CRON_PROFILE = canary

